---
title: "Research Training & Experience"
---
### Student Researcher (present)
**Project:** Sleep and Social Media Use across sporting levels

**Supervisor:** [Dr Heather Cleland Woods](https://www.gla.ac.uk/schools/psychology/staff/heatherwoods/)

**Duties:** reviewed literature, developed a proposal and considered ethical implications; currently: recruit participants, collect data via online questionnaire, wrangle data and carry out statistical analysis, report and discuss results in a thesis and prepare them for a journal article

### Adjunct Researcher (2017 – present)
**Project:** BIPO 400

**Supervisor:** [MuDr. Filip Španiel](https://www.researchgate.net/profile/Filip_Spaniel)

**Duties:** support a team conducting a large clinical study investigating circadian rhythms in individuals with bipolar disorder; recruit participants, contribute to methodology development (literature review, participant feedback), conduct phone-based clinical interviews and score participants‘ mood, provide technical support for participants using mobile app and actigraphy 

RP5 Sleep Medicine and Chronobiology

National Institute of Mental Health (NIMH), Czech Republic

### Clinical Studies Coordinator (2017)
**Duties:** cooperated closely with NIMH researchers, designing a large clinical study investigating circadian rhythms in individuals with bipolar disorder; defined processes, work-flow and responsibilities of all participating parties; provided operational support and facilitated communication between all parties on behalf of Mindpax; recruited Coordinators and Assistants 

[Mindpax](https://mindpax.me/en/), Czech Republic

###Interdisciplinary Summer School: The Everyday City and Beyond (July 2017)
Content: the practice, theory, policies and politics of ‘placemaking,' taking Amsterdam as a site for analysis and action

**Project:** Bridging the social gap between tourists and locals at the site of Rembrandtplein

**Skills involved:** observation, mapping, interviewing, stakeholder analysis, visual and tangible presentation of the final project (prototyping)   

University of Amsterdam, the Netherlands 


### Summer Research Internship (2016)
**Project:** The role of chronotype and sleep hygiene in the treatment of obesity 

**Supervisor:** [Ing. Mgr. Eva Fárková](http://www.nudz.cz/en/employee/?id=521)

**Duties:** digitised and scored collected data (sleep diaries and questionnaires), organised qualitative and quantitative data for further analysis

RP5 Sleep Medicine and Chronobiology & RP7 Diagnostics and Treatment of Mental Disorders 

National Institute of Mental Health (NIMH), Czech Republic 


